Add new button for generating http connections and components
metadew/iesi-ui pull request #45
Opened 2021-03-26 08:07 UTC by hkhattabii

**Styles**
The button and the tooltip will be made from the **material-ui library**

**Button position**

The button will be placed on the left of the "create script" button with a small spacing and aligned with it. 
 
**On mouse hover**

When the mouse hover the button, a **tooltip** appears to provide more information about the button.
This **tooltip** will be displayed on the top of the button. It will have black background color and white text color.
The **tooltip** appear with a transition animation that can be user-friendly.

**On mouse cursor leave**

When the mouse cursor leave the button, the tooltip disappears with also a transition animation.

**On mouse click**
When the button is triggered, a new page will appear that display the empty information of the documentation transformation.

**UI Vizualisation**

![Index](https://user-images.githubusercontent.com/54418529/112296535-50e2f900-8c95-11eb-957e-5652ef1b2b31.png)

2021-03-26 11:38 UTC, hkhattabii commented on src/views/design/ScriptsOverview/index.tsx
> +                                                        title="Transform an OpenAPI documentation into IESI concept"
I just have seen how to render the translation without rendering the Translate component, I will change this line later

2021-03-30 09:42 UTC, BerrevoetsRobbe requested changes

2021-03-30 09:42 UTC, BerrevoetsRobbe commented on src/views/translations/en_GB.yml
> +      transform_openapi_tooltip: "Transform an OpenAPI documentation into IESI concept"
"Transform an OpenAPI documentation into IESI connections and components"

2021-03-30 09:42 UTC, BerrevoetsRobbe commented on src/views/translations/en_GB.yml
> +      generate_button: "Generate connections and components"
Load OpenAPI documentation

2021-03-30 09:42 UTC, BerrevoetsRobbe commented on src/views/design/ScriptsOverview/index.tsx
> +                                                </Box>
make sure text is visible on 1 line

2021-03-30 09:42 UTC, BerrevoetsRobbe commented on src/views/design/ScriptsOverview/index.tsx
>                                      {checkAuthorityGeneral(SECURITY_PRIVILEGES.S_SCRIPTS_WRITE)
the 'load OpenAPI' button should appear if you have CONNECTIONS_WRITE or COMPONENTS_WRITE privilege.
The 'add button " button should appear if you have SCRIPTS_WRITE privilige (as is situation)

2021-04-12 08:06 UTC, closed without merging